{% set name = "mordredcommunity" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mordredcommunity-{{ version }}.tar.gz
  sha256: 36dc5e586ab400516d5d805c20346e48e80dc354fce39e46cb6f42d6c53dad52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - pip
  run:
    - python >=3.8
    - rdkit
    - six
    - numpy
    - networkx
    - packaging
    - pandas

test:
  imports:
    - mordred

about:
  home: https://github.com/JacksonBurns/mordred-community
  summary: Community-Maintained Version of mordred
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JacksonBurns
