{% set name = "mordredcommunity" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mordredcommunity-{{ version }}.tar.gz
  sha256: a697866278b606b25012e62492e9e17ace50355618edb8686090365336cda3df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - pip
  run:
    - python >=3.8
    - rdkit
    - six
    - numpy
    - networkx
    - packaging
    - pandas

test:
  imports:
    - mordred

about:
  home: https://github.com/JacksonBurns/mordred-community
  summary: Community-Maintained Version of mordred
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JacksonBurns
