{% set name = "mordredcommunity" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mordredcommunity-{{ version }}.tar.gz
  sha256: e8f8ed6c1c3c98aeb3e8a2c48240c7b7df6acf777a2ff8bc8bd0a1b3f44cf6ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - pip
  run:
    - python >=3.8
    - rdkit
    - six
    - numpy
    - networkx
    - packaging
    - pandas

test:
  imports:
    - mordred

about:
  home: https://github.com/JacksonBurns/mordred-community
  summary: Community-Maintained Version of mordred
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JacksonBurns
